apiVersion: tekton.dev/v1
kind: Task
spec:
  steps:
  - image: busybox
    script: echo "$(context.task.name), step 1"
  - image: busybox
    script: echo "$(context.task.name), step 2"
  - image: busybox
    script: echo "$(context.task.name), step 3"
  - image: busybox
    script: echo "$(context.task.name), step 4"
  - image: busybox
    script: echo "$(context.task.name), step 5"
  - image: busybox
    script: echo "$(context.task.name), step 6"
  - image: busybox
    script: echo "$(context.task.name), step 7"
  - image: busybox
    script: echo "$(context.task.name), step 8"
  - image: busybox
    script: echo "$(context.task.name), step 9"
  - image: busybox
    script: echo "$(context.task.name), step 10"
  - image: busybox
    script: echo "$(context.task.name), step 11"
  - image: busybox
    script: echo "$(context.task.name), step 12"
  - image: busybox
    script: echo "$(context.task.name), step 13"
  - image: busybox
    script: echo "$(context.task.name), step 14"
  - image: busybox
    script: echo "$(context.task.name), step 15"
  - image: busybox
    script: echo "$(context.task.name), step 16"
  - image: busybox
    script: echo "$(context.task.name), step 17"
  - image: busybox
    script: echo "$(context.task.name), step 18"
  - image: busybox
    script: echo "$(context.task.name), step 19"
  - image: busybox
    script: echo "$(context.task.name), step 20"
  - image: busybox
    script: echo "$(context.task.name), step 21"
  - image: busybox
    script: echo "$(context.task.name), step 22"
  - image: busybox
    script: echo "$(context.task.name), step 23"
  - image: busybox
    script: echo "$(context.task.name), step 24"
  - image: busybox
    script: echo "$(context.task.name), step 25"
  - image: busybox
    script: echo "$(context.task.name), step 26"
  - image: busybox
    script: echo "$(context.task.name), step 27"
  - image: busybox
    script: echo "$(context.task.name), step 28"
  - image: busybox
    script: echo "$(context.task.name), step 29"
  - image: busybox
    script: echo "$(context.task.name), step 30"
  - image: busybox
    script: echo "$(context.task.name), step 31"
  - image: busybox
    script: echo "$(context.task.name), step 32"
  - image: busybox
    script: echo "$(context.task.name), step 33"
  - image: busybox
    script: echo "$(context.task.name), step 34"
  - image: busybox
    script: echo "$(context.task.name), step 35"
  - image: busybox
    script: echo "$(context.task.name), step 36"
  - image: busybox
    script: echo "$(context.task.name), step 37"
  - image: busybox
    script: echo "$(context.task.name), step 38"
  - image: busybox
    script: echo "$(context.task.name), step 39"
  - image: busybox
    script: echo "$(context.task.name), step 40"
  - image: busybox
    script: echo "$(context.task.name), step 41"
  - image: busybox
    script: echo "$(context.task.name), step 42"
  - image: busybox
    script: echo "$(context.task.name), step 43"
  - image: busybox
    script: echo "$(context.task.name), step 44"
  - image: busybox
    script: echo "$(context.task.name), step 45"
  - image: busybox
    script: echo "$(context.task.name), step 46"
  - image: busybox
    script: echo "$(context.task.name), step 47"
  - image: busybox
    script: echo "$(context.task.name), step 48"
  - image: busybox
    script: echo "$(context.task.name), step 49"
  - image: busybox
    script: echo "$(context.task.name), step 50"
  - image: busybox
    script: echo "$(context.task.name), step 51"
  - image: busybox
    script: echo "$(context.task.name), step 52"
  - image: busybox
    script: echo "$(context.task.name), step 53"
  - image: busybox
    script: echo "$(context.task.name), step 54"
  - image: busybox
    script: echo "$(context.task.name), step 55"
  - image: busybox
    script: echo "$(context.task.name), step 56"
  - image: busybox
    script: echo "$(context.task.name), step 57"
  - image: busybox
    script: echo "$(context.task.name), step 58"
  - image: busybox
    script: echo "$(context.task.name), step 59"
  - image: busybox
    script: echo "$(context.task.name), step 60"
  - image: busybox
    script: echo "$(context.task.name), step 61"
  - image: busybox
    script: echo "$(context.task.name), step 62"
  - image: busybox
    script: echo "$(context.task.name), step 63"
  - image: busybox
    script: echo "$(context.task.name), step 64"
  - image: busybox
    script: echo "$(context.task.name), step 65"
  - image: busybox
    script: echo "$(context.task.name), step 66"
  - image: busybox
    script: echo "$(context.task.name), step 67"
  - image: busybox
    script: echo "$(context.task.name), step 68"
  - image: busybox
    script: echo "$(context.task.name), step 69"
  - image: busybox
    script: echo "$(context.task.name), step 70"
  - image: busybox
    script: echo "$(context.task.name), step 71"
  - image: busybox
    script: echo "$(context.task.name), step 72"
  - image: busybox
    script: echo "$(context.task.name), step 73"
  - image: busybox
    script: echo "$(context.task.name), step 74"
  - image: busybox
    script: echo "$(context.task.name), step 75"
  - image: busybox
    script: echo "$(context.task.name), step 76"
  - image: busybox
    script: echo "$(context.task.name), step 77"
  - image: busybox
    script: echo "$(context.task.name), step 78"
  - image: busybox
    script: echo "$(context.task.name), step 79"
  - image: busybox
    script: echo "$(context.task.name), step 80"
  - image: busybox
    script: echo "$(context.task.name), step 81"
  - image: busybox
    script: echo "$(context.task.name), step 82"
  - image: busybox
    script: echo "$(context.task.name), step 83"
  - image: busybox
    script: echo "$(context.task.name), step 84"
  - image: busybox
    script: echo "$(context.task.name), step 85"
  - image: busybox
    script: echo "$(context.task.name), step 86"
  - image: busybox
    script: echo "$(context.task.name), step 87"
  - image: busybox
    script: echo "$(context.task.name), step 88"
  - image: busybox
    script: echo "$(context.task.name), step 89"
  - image: busybox
    script: echo "$(context.task.name), step 90"
  - image: busybox
    script: echo "$(context.task.name), step 91"
  - image: busybox
    script: echo "$(context.task.name), step 92"
  - image: busybox
    script: echo "$(context.task.name), step 93"
  - image: busybox
    script: echo "$(context.task.name), step 94"
  - image: busybox
    script: echo "$(context.task.name), step 95"
  - image: busybox
    script: echo "$(context.task.name), step 96"
  - image: busybox
    script: echo "$(context.task.name), step 97"
  - image: busybox
    script: echo "$(context.task.name), step 98"
  - image: busybox
    script: echo "$(context.task.name), step 99"
